# Generated by Django 4.0.3 on 2022-03-18 17:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Myneighbor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='neighbor',
            name='occupation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('post', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('neighbor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Myneighbor.neighbor')),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('neighbor', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Myneighbor.neighbor')),
            ],
        ),
    ]
