# Generated by Django 4.0.3 on 2022-03-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myneighbor', '0002_alter_neighbor_location_alter_neighbor_occupation_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
