# Generated by Django 4.0.3 on 2022-03-19 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('Myneighbor', '0004_neighbor_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='neighbor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
