# Generated by Django 4.0.3 on 2022-03-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myneighbor', '0005_neighbor_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbor',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='neighbor',
            name='occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
