# Generated by Django 4.0.3 on 2022-03-20 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myneighbor', '0007_business_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Business',
        ),
    ]
